### ISSUE TITLE
add metric: branch protections restrict the source

### ISSUE THREAD

**Issue by ljharb** [ljharb/repo-report#62]
Individual branch protections can now restrict to a specific source (github app) instead of "any source".

A metric we should add is "percentage of branch protections that are restricted", with the default being 100.

**Comment by MaheraFurniturewala** [comment]
I'd like to work on this issue.

**Comment by PriyaBihani** [comment]
I wan't to work along with Mahira on this issue.

**Comment by MaheraFurniturewala** [comment]
Hey @ljharb!
Would be great if you could explain what you mean by - restricting to a specific source instead of "any source".

**Comment by ljharb** [comment]
@MaheraFurniturewala in branch protection settings:
<img width="757" alt="Screen Shot 2022-03-20 at 8 50 33 PM" src="https://user-images.githubusercontent.com/45469/159203025-3b731758-95f2-439a-9ed3-aba1548b2f03.png">

**Comment by PriyaBihani** [comment]
@ljharb  Can you also explain how to calculate the percentage?

**Comment by ljharb** [comment]
In this example, there’s 5 checks, and 60% of them have a required source.

**Comment by PriyaBihani** [comment]
@ljharb Here we referring source to github remote right?

**Comment by ljharb** [comment]
No - the "source" in this case is the Github App generating the status check. For example, Github Actions, Codecov, etc.

**Comment by PriyaBihani** [comment]
<pre>
query {
  viewer {
	repositories(
	  first: 100
	  affiliations: [OWNER, ORGANIZATION_MEMBER, COLLABORATOR]) {
	  totalCount
	  pageInfo {
		endCursor
		hasNextPage
	}
	nodes {
		name
		nameWithOwner
		defaultBranchRef {
			name
			branchProtectionRule {
				allowsForcePushes
				allowsDeletions
				dismissesStaleReviews
				requiredApprovingReviewCount
				requiresApprovingReviews
				requiresCodeOwnerReviews
				requiresConversationResolution
				restrictsPushes
                                requiredStatusChecks {
                                 app {
                                     id
                                 }
                              }
			}
		}
	  }
	}
  }
}
</pre>
Hey @ljharb  This query might be useful for getting the status checks and their apps. But I can't test it right now, as I don't have any repository that have checks and branch protection set up. Can you help me out with this?

**Comment by ljharb** [comment]
@PriyaBihani do you mean help you set up a repo with them? you can copy the workflow files from this repo, and then once they've ran, they'll show up as an option in branch protections. Otherwise, we can grab some pairing time after next week.
