### ISSUE TITLE
Loading/progress bar

### ISSUE THREAD

**Issue by khattakdev** [ljharb/repo-report#80]
When you execute the script (`bin/run`), it takes some time to display the result due, depending on the number of repositories. I think it's a good idea to add a progress bar otherwise, it looks like the terminal is stuck.

**Comment by ljharb** [comment]
Displaying something is a good idea. I’m not sure how we’d do a progress bar since we have no idea how long the query is expected to take - also, i wouldn’t want to clear the console after the request comes back, because that’s disruptive, but i also wouldn’t want to leave the progress indicator visible above the table.

Open to ideas!

**Comment by khattakdev** [comment]
How about this:

```
Loading...
Loading completed!
```

**Comment by ljharb** [comment]
That's fine for initial output, but it'd be nice to find a way to remove that output once the table is ready without `console.clear()`.

**Comment by khattakdev** [comment]
@ljharb One of the solution which I suggested to @abdumamdouh yesterday is to save the user's command and show the loading screen.

Once the loading is complete, clear the console. print the user's command and print the data.
```
npx report-report
Loading...
```

Once the loading is complete
```
npx repo-report
{Repositories details}
```

**Comment by abdumamdouh** [comment]
@khattakdev @ljharb 

1-take input, ex: repo-report --version
2-store it in var
3-dispaly "Loading..." while fetching
4-done fetching
5-display "Loading completed!" or skip this step
6-then clear console 
7-then display input 
8-then display results

**Comment by ljharb** [comment]
It would be ideal to avoid ever clearing the console - i like seeing my previous commands' output, and it's pretty disruptive for a program to clear that.

**Comment by abdumamdouh** [comment]
@ljharb so what do you recommend?

**Comment by ljharb** [comment]
That's what I'm not sure about :-)

I'm wondering if there's something to be done with `printf` so that we print progress on a single line, and then overwrite just that one line to print the table?
